blank_issues_enabled: false
contact_links:
  - name: Exploding Kittens Discussions
    url: https://github.com/sanwenyukaochi/Exploding-Kittens/discussions
    about: Please ask and answer questions here.
