package com.kittens.exploding.common.base_domain;

import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum ActivityType {
    UNUSED("Unused"),
    DEATH("Death"),
    CHOOSING_TARGET_STEAL("ChoosingTargetSteal"),
    CHOOSING_TARGET_DIARRHEA("ChoosingTargetDiarrhea"),
    CHOOSING_TARGET_CAT_BUTT("ChoosingTargetCatButt"),
    CHOOSING_TARGET_SLAP("ChoosingTargetSlap"),
    RECEIVED_STEAL("ReceivedSteal"),
    SAW_THE_FUTURE("SawTheFuture"),
    DREW_FROM_BOTTOM("DrewFromBottom"),
    SKIPPED_DRAWING("SkippedDrawing"),
    SPRAYED_CARDS_WITH_DIARRHEA("SprayedCardsWithDiarrhea"),
    CHOOSING_CARD_STEAL("ChoosingCardSteal"),
    CHOOSING_KITTEN_PLACEMENT("ChoosingKittenPlacement"),
    REVERSED_TURN_DIRECTION("ReversedTurnDirection"),
    SHUFFLED_DRAW_PILE("ShuffledDrawPile"),
    START_TURN("StartTurn"),
    ATTACK_CAT_BUTT("AttackCatButt"),
    ATTACK_CAT_BUTT_ENDED("AttackCatButtEnded"),
    ATTACK("Attack"),
    TIMED_OUT("TimedOut"),
    STEAL_TARGET_DISCONNECTED("StealTargetDisconnected"),
    KITTEN_ROLL_CALL("KittenRollCall"),
    NEXT_CARD_IS_RANDOM("NextCardIsRandom"),
    ALTER_THE_FUTURE("AlterTheFuture"),
    WASTED_ALTER_THE_FUTURE("WastedAlterTheFuture"),
    TURNS_LEFT_NOTIFICATION("TurnsLeftNotification"),
    SWAP_TOP_BOTTOM("SwapTopBottom"),
    MARK_CARD("MarkCard"),
    CHOOSING_MARKED_CARD("ChoosingMarkedCard"),
    WAITING_FOR_GARBAGE("WaitingForGarbage"),
    CATOMIC_BOMB("CatomicBomb"),
    SUPER_SKIP("SuperSkip"),
    GARBAGE_SHUFFLE("GarbageShuffle"),
    STREAKING("Streaking"),
    STILL_YOUR_TURN("StillYourTurn"),
    WAITING_FOR_OTHERS_GARBAGE("WaitingForOthersGarbage"),
    GIVEN_BOMB_FOR_STEAL("GivenBombForSteal"),
    CARD_DISCARDED("CardDiscarded"),
    TWO_DEFUSE_NEEDED("TwoDefuseNeeded"),
    DEFUSE_KITTEN("DefuseKitten"),
    OPPONENT_DEFUSE_KITTEN("OpponentDefuseKitten"),
    SHUFFLED_STREAKING("ShuffledStreaking"),
    STILL_THEIR_TURN("StillTheirTurn"),
    WASTED_DRAW_FROM_BOTTOM("WastedDrawFromBottom"),
    WASTED_SHUFFLE("WastedShuffle"),
    WASTED_FAKE_SHUFFLE("WastedFakeShuffle"),
    WASTED_CAT_BUTT("WastedCatButt"),
    WASTED_GARBAGE_COLLECTION("WastedGarbageCollection"),
    WASTED_DIARRHEA("WastedDiarrhea"),
    WASTED_SWAP_TOP_BOTTOM("WastedSwapTopBottom"),
    BLIND_DRAW_FROM_BOTTOM_BOMB("BlindDrawFromBottomBomb"),
    GIVE_BOMB_FOR_STEAL("GiveBombForSteal"),
    BARKING_ALONE("BarkingAlone"),
    BARKING_WAITING("BarkingWaiting"),
    BARKING_RECEIVED("BarkingReceived"),
    BARKING_CHOOSE_CARD("BarkingChooseCard"),
    TAKE_THAT_CHOOSE_TARGET("TakeThatChooseTarget"),
    TAKE_THAT_TARGET_CHOSEN("TakeThatTargetChosen"),
    TOWER_OF_POWER("TowerOfPower"),
    WAITING_FOR_POT_LUCK("WaitingForPotLuck"),
    WAITING_FOR_OTHERS_POT_LUCK("WaitingForOthersPotLuck"),
    POT_LUCK_DONE("PotLuckDone"),
    SHARING_FUTURE("SharingFuture"),
    DEFUSE_BARKING("DefuseBarking"),
    OPPONENT_DEFUSE_BARKING("OpponentDefuseBarking"),
    BARKING_EXPLODED("BarkingExploded"),
    BARKING_DEFUSED("BarkingDefused");

    private final String value;
}