using System.Collections;
using System.ComponentModel;

namespace System.Data
{
	[DefaultEvent("CollectionChanged")]
	public sealed class ConstraintCollection : InternalDataCollectionBase
	{
		private readonly DataTable _table;

		private readonly ArrayList _list;

		private int _defaultNameIndex;

		private CollectionChangeEventHandler _onCollectionChanged;

		private Constraint[] _delayLoadingConstraints;

		private bool _fLoadForeignKeyConstraintsOnly;

		protected override ArrayList List => null;

		public Constraint this[int index] => null;

		internal DataTable Table => null;

		public Constraint this[string name] => null;

		internal ConstraintCollection(DataTable table)
		{
		}

		public void Add(Constraint constraint)
		{
		}

		internal void Add(Constraint constraint, bool addUniqueWhenAddingForeign)
		{
		}

		public Constraint Add(string name, DataColumn[] columns, bool primaryKey)
		{
			return null;
		}

		private void AddUniqueConstraint(UniqueConstraint constraint)
		{
		}

		private void AddForeignKeyConstraint(ForeignKeyConstraint constraint)
		{
		}

		private bool AutoGenerated(Constraint constraint)
		{
			return false;
		}

		private void ArrayAdd(Constraint constraint)
		{
		}

		private void ArrayRemove(Constraint constraint)
		{
		}

		internal string AssignName()
		{
			return null;
		}

		private void BaseAdd(Constraint constraint)
		{
		}

		private void BaseGroupSwitch(Constraint[] oldArray, int oldLength, Constraint[] newArray, int newLength)
		{
		}

		private void BaseRemove(Constraint constraint)
		{
		}

		internal bool CanRemove(Constraint constraint, bool fThrowException)
		{
			return false;
		}

		public void Clear()
		{
		}

		public bool Contains(string name)
		{
			return false;
		}

		internal bool Contains(string name, bool caseSensitive)
		{
			return false;
		}

		internal Constraint FindConstraint(Constraint constraint)
		{
			return null;
		}

		internal UniqueConstraint FindKeyConstraint(DataColumn[] columns)
		{
			return null;
		}

		internal UniqueConstraint FindKeyConstraint(DataColumn column)
		{
			return null;
		}

		internal ForeignKeyConstraint FindForeignKeyConstraint(DataColumn[] parentColumns, DataColumn[] childColumns)
		{
			return null;
		}

		private static bool CompareArrays(DataColumn[] a1, DataColumn[] a2)
		{
			return false;
		}

		internal int InternalIndexOf(string constraintName)
		{
			return 0;
		}

		private string MakeName(int index)
		{
			return null;
		}

		private void OnCollectionChanged(CollectionChangeEventArgs ccevent)
		{
		}

		internal void RegisterName(string name)
		{
		}

		public void Remove(Constraint constraint)
		{
		}

		internal void UnregisterName(string name)
		{
		}

		internal void FinishInitConstraints()
		{
		}
	}
}
