using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace System.Data
{
	[TypeConverter(typeof(RelationshipConverter))]
	[DefaultProperty("RelationName")]
	public class DataRelation
	{
		private DataSet _dataSet;

		internal PropertyCollection _extendedProperties;

		internal string _relationName;

		private DataKey _childKey;

		private DataKey _parentKey;

		private UniqueConstraint _parentKeyConstraint;

		private ForeignKeyConstraint _childKeyConstraint;

		internal string[] _parentColumnNames;

		internal string[] _childColumnNames;

		internal string _parentTableName;

		internal string _childTableName;

		internal string _parentTableNamespace;

		internal string _childTableNamespace;

		internal bool _nested;

		internal bool _createConstraints;

		private bool _checkMultipleNested;

		private static int s_objectTypeCount;

		private readonly int _objectID;

		[CompilerGenerated]
		private PropertyChangedEventHandler PropertyChanging;

		public virtual DataColumn[] ChildColumns => null;

		internal DataColumn[] ChildColumnsReference => null;

		internal DataKey ChildKey => default(DataKey);

		public virtual DataTable ChildTable => null;

		[DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
		[Browsable(false)]
		public virtual DataSet DataSet => null;

		internal string[] ParentColumnNames => null;

		internal string[] ChildColumnNames => null;

		public virtual DataColumn[] ParentColumns => null;

		internal DataColumn[] ParentColumnsReference => null;

		internal DataKey ParentKey => default(DataKey);

		public virtual DataTable ParentTable => null;

		[DefaultValue(null)]
		public virtual string RelationName => null;

		[DefaultValue(false)]
		public virtual bool Nested
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		public virtual UniqueConstraint ParentKeyConstraint => null;

		public virtual ForeignKeyConstraint ChildKeyConstraint => null;

		[Browsable(false)]
		public PropertyCollection ExtendedProperties => null;

		internal bool CheckMultipleNested
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		internal int ObjectID => 0;

		public DataRelation(string relationName, DataColumn parentColumn, DataColumn childColumn, bool createConstraints)
		{
		}

		public DataRelation(string relationName, DataColumn[] parentColumns, DataColumn[] childColumns)
		{
		}

		public DataRelation(string relationName, DataColumn[] parentColumns, DataColumn[] childColumns, bool createConstraints)
		{
		}

		[Browsable(false)]
		public DataRelation(string relationName, string parentTableName, string childTableName, string[] parentColumnNames, string[] childColumnNames, bool nested)
		{
		}

		[Browsable(false)]
		public DataRelation(string relationName, string parentTableName, string parentTableNamespace, string childTableName, string childTableNamespace, string[] parentColumnNames, string[] childColumnNames, bool nested)
		{
		}

		private static bool IsKeyNull(object[] values)
		{
			return false;
		}

		internal static DataRow[] GetChildRows(DataKey parentKey, DataKey childKey, DataRow parentRow, DataRowVersion version)
		{
			return null;
		}

		internal static DataRow[] GetParentRows(DataKey parentKey, DataKey childKey, DataRow childRow, DataRowVersion version)
		{
			return null;
		}

		internal static DataRow GetParentRow(DataKey parentKey, DataKey childKey, DataRow childRow, DataRowVersion version)
		{
			return null;
		}

		internal void SetDataSet(DataSet dataSet)
		{
		}

		internal void CheckNamespaceValidityForNestedRelations(string ns)
		{
		}

		internal void CheckNestedRelations()
		{
		}

		internal void SetParentKeyConstraint(UniqueConstraint value)
		{
		}

		internal void SetChildKeyConstraint(ForeignKeyConstraint value)
		{
		}

		internal void CheckState()
		{
		}

		protected void CheckStateForProperty()
		{
		}

		private void Create(string relationName, DataColumn[] parentColumns, DataColumn[] childColumns, bool createConstraints)
		{
		}

		internal DataRelation Clone(DataSet destination)
		{
			return null;
		}

		protected internal void OnPropertyChanging(PropertyChangedEventArgs pcevent)
		{
		}

		protected internal void RaisePropertyChanging(string name)
		{
		}

		public override string ToString()
		{
			return null;
		}

		internal void ValidateMultipleNestedRelations()
		{
		}

		private bool IsAutoGenerated(DataColumn col)
		{
			return false;
		}
	}
}
